framework:
    secret: '%env(APP_SECRET)%'
    assets:
        # feature is supported in Symfony 3.3 and higher : used by encore for example with npm run dev-server command
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    #session:
    #    # The native PHP session handler will be used
    #    handler_id: ~
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
