dist: trusty
sudo: required

addons:
  chrome: stable
  srcclr: true
#  apt:
#    packages:
#      - nginx
#      - php-fpm

env:
  global:
    - SERVER_HOST_WEB="localhost:80"

language: php
php:
  - 7.1

before_install:
  - sudo ps aux | grep php-fpm
  - sudo ls /etc/init.d
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  - sudo apt-get update
  - sudo apt-get install nginx
  - sudo apt-get install php7.1-fpm
  - pwd
  - sudo cp var/travis/nginx.conf /etc/nginx/sites-available/$SERVER_HOST_WEB.conf
  - sudo ln -s /etc/nginx/sites-available/$SERVER_HOST_WEB /etc/nginx/sites-enabled/
  - nvm install 8.9.0
  - nvm use 8.9.0

install:
  - npm run init-project
  - npm run dev

before_script:
#  - curl -H "Accept: application/json" https://security.sensiolabs.org/check_lock -F lock=@composer.lock
  - sudo service php7.1-fpm restart
  - sudo service nginx restart

script:
  - npm test

notifications:
  email: false